### ISSUE TITLE
Availability check failing for InfluxDB v1 (after recent changes)

### ISSUE THREAD

**Issue by sumnerboy12** [tiredofit/docker-db-backup#118]
### Summary

Unable to backup InfluxDB v1 after recent changes to support v2. See error below. The `/health` endpoint doesn't appear to exist on InfluxDB v1.

### Steps to reproduce

Attempt to backup an InfluxDB v1 database.

### What is the expected *correct* behavior?

Backup succeeds.

### Relevant logs and/or screenshots

```
[tiredofit/db-backup:3.2.1 13:10:28] # backup-now 
** Performing Manual Backup
2022-04-14.13:10:33 [DEBUG] ** [db-backup] Looking for existence of INFLUX_VERSION environment variable
2022-04-14.13:10:33 [DEBUG] ** [db-backup] Detected Manual Mode
2022-04-14.13:10:33 [DEBUG] ** [db-backup] Backup routines started time: 2022-04-14 13:10:33 NZST
curl: (56) Recv failure: Connection reset by peer
2022-04-14.13:10:38 [WARN] ** [db-backup] InfluxDB Host 'http://db' is not accessible, retrying.. (5 seconds so far)
curl: (56) Recv failure: Connection reset by peer
2022-04-14.13:10:43 [WARN] ** [db-backup] InfluxDB Host 'http://db' is not accessible, retrying.. (10 seconds so far)
curl: (56) Recv failure: Connection reset by peer
```

### Environment

I tried both `DB_HOST=db` and `DB_HOST=http://db`.

```
INFLUX_VERSION=1

DB_TYPE=influx
DB_HOST=http://db
DB_PORT=8088
DB_NAME=openhab
DB_USER=secret
DB_PASS=secret
```

- Image version / tag: latest  
- Host OS: docker
    
### Possible fixes

I think you need to revert to the `nc` check for InfluxDB v1 as the `/health` endpoint doesn't appear to exist on InfluxDB v1.

**Comment by tiredofit** [comment]
What version of Influx are you using? I introduced the check on /health due to the documentation matching for both [1.8](https://docs.influxdata.com/influxdb/v1.8/tools/api/#health-http-endpoint) and [2.x](https://docs.influxdata.com/flux/v0.x/stdlib/experimental/influxdb/api/#retrieve-the-health-of-an-influxdb-oss-instance)

**Comment by sumnerboy12** [comment]
I am using `influxdb:1.8`. I had set the `DB_PORT` to 8088 which I think is why the `/heath` check was failing. I just changed it to 8086 and now that check is passing but I am getting the following error;

```
2022-04-16.07:17:39 [NOTICE] ** [db-backup] Dumping Influx database: 'openhab'
flag provided but not defined: -bucket

Creates a backup copy of specified InfluxDB OSS database(s) and saves the files in an Enterprise-compatible
format to PATH (directory where backups are saved). 

Usage: influxd backup [options] PATH

    -portable
            Required to generate backup files in a portable format that can be restored to InfluxDB OSS or InfluxDB 
            Enterprise. Use unless the legacy backup is required.
    -host <host:port>
            InfluxDB OSS host to back up from. Optional. Defaults to 127.0.0.1:8088.
    -db <name>
            InfluxDB OSS database name to back up. Optional. If not specified, all databases are backed up when 
            using '-portable'.
```

So it looks like the `-bucket` argument doesn't exist. I changed to `DB_NAME=ALL` and now get;

```
[tiredofit/db-backup:3.2.1 07:20:48] # backup-now
** Performing Manual Backup
2022-04-16.07:20:59 [DEBUG] ** [db-backup] Looking for existence of INFLUX_VERSION environment variable
2022-04-16.07:20:59 [DEBUG] ** [db-backup] Detected Manual Mode
2022-04-16.07:20:59 [DEBUG] ** [db-backup] Backup routines started time: 2022-04-16 07:20:59 NZST
2022-04-16.07:20:59 [DEBUG] ** [db-backup] Preparing to back up everything
2022-04-16.07:20:59 [NOTICE] ** [db-backup] Dumping Influx database: 'all'
2022/04/16 07:20:59 backing up metastore to /tmp/backups/influx_all_db_20220416-072059/meta.00
2022/04/16 07:20:59 Invalid metadata blob, ensure the metadata service is running (default port 8088)
backup: invalid metadata received
2022-04-16.07:20:59 [DEBUG] ** [db-backup] DB Backup Exit Code is 1
2022-04-16.07:20:59 [ERROR] ** [db-backup] DB Backup of 'influx_all_db_20220416-072059' reported errors
```

In short, there are two ports needed since InfluxDB v1.8 exposes the REST API on 8086 and the RPC service on 8088...

**Comment by tiredofit** [comment]
Thanks for the legwork on this - I will revert to the standard netcat statement for `INFLUX_VERSION=1` on next release.

**Comment by tiredofit** [comment]
Resolved in `tiredofit/db-backup:3.2.2` - Please close when confirmed

**Comment by sumnerboy12** [comment]
Still failing if I specify a specific database to backup... (will try now with `DB_NAME=ALL`)
```
openhab_db-backup.1.suvurwfeo7kk@nuc02    | 2022-04-22.09:39:08 [DEBUG] ** [db-backup] Backup routines started time: 2022-04-22 09:39:08 NZST
openhab_db-backup.1.suvurwfeo7kk@nuc02    | 2022-04-22.09:39:08 [NOTICE] ** [db-backup] Dumping Influx database: 'openhab'
openhab_db-backup.1.suvurwfeo7kk@nuc02    |
openhab_db-backup.1.suvurwfeo7kk@nuc02    | Creates a backup copy of specified InfluxDB OSS database(s) and saves the files in an Enterprise-compatible
openhab_db-backup.1.suvurwfeo7kk@nuc02    | format to PATH (directory where backups are saved).
openhab_db-backup.1.suvurwfeo7kk@nuc02    |
openhab_db-backup.1.suvurwfeo7kk@nuc02    | Usage: influxd backup [options] PATH
openhab_db-backup.1.suvurwfeo7kk@nuc02    |
openhab_db-backup.1.suvurwfeo7kk@nuc02    |     -portable
openhab_db-backup.1.suvurwfeo7kk@nuc02    |             Required to generate backup files in a portable format that can be restored to InfluxDB OSS or InfluxDB
openhab_db-backup.1.suvurwfeo7kk@nuc02    |             Enterprise. Use unless the legacy backup is required.
openhab_db-backup.1.suvurwfeo7kk@nuc02    |     -host <host:port>
openhab_db-backup.1.suvurwfeo7kk@nuc02    |             InfluxDB OSS host to back up from. Optional. Defaults to 127.0.0.1:8088.
openhab_db-backup.1.suvurwfeo7kk@nuc02    |     -db <name>
openhab_db-backup.1.suvurwfeo7kk@nuc02    |             InfluxDB OSS database name to back up. Optional. If not specified, all databases are backed up when
openhab_db-backup.1.suvurwfeo7kk@nuc02    |             using '-portable'.
openhab_db-backup.1.suvurwfeo7kk@nuc02    |     -rp <name>
openhab_db-backup.1.suvurwfeo7kk@nuc02    |             Retention policy to use for the backup. Optional. If not specified, all retention policies are used by
openhab_db-backup.1.suvurwfeo7kk@nuc02    |             default.
openhab_db-backup.1.suvurwfeo7kk@nuc02    |     -shard <id>
openhab_db-backup.1.suvurwfeo7kk@nuc02    |             The identifier of the shard to back up. Optional. If specified, '-rp <rp_name>' is required.
openhab_db-backup.1.suvurwfeo7kk@nuc02    |     -start <2015-12-24T08:12:23Z>
openhab_db-backup.1.suvurwfeo7kk@nuc02    |             Include all points starting with specified timestamp (RFC3339 format).
openhab_db-backup.1.suvurwfeo7kk@nuc02    |             Not compatible with '-since <timestamp>'.
openhab_db-backup.1.suvurwfeo7kk@nuc02    |     -end <2015-12-24T08:12:23Z>
openhab_db-backup.1.suvurwfeo7kk@nuc02    | flag provided but not defined: -bucket
openhab_db-backup.1.suvurwfeo7kk@nuc02    | backup: flag provided but not defined: -bucket
openhab_db-backup.1.suvurwfeo7kk@nuc02    |             Exclude all points after timestamp (RFC3339 format).
openhab_db-backup.1.suvurwfeo7kk@nuc02    |             Not compatible with '-since <timestamp>'.
openhab_db-backup.1.suvurwfeo7kk@nuc02    |     -since <2015-12-24T08:12:23Z>
openhab_db-backup.1.suvurwfeo7kk@nuc02    |             Create an incremental backup of all points after the timestamp (RFC3339 format). Optional.
openhab_db-backup.1.suvurwfeo7kk@nuc02    |             Recommend using '-start <timestamp>' instead.
openhab_db-backup.1.suvurwfeo7kk@nuc02    |     -skip-errors
openhab_db-backup.1.suvurwfeo7kk@nuc02    |             Optional flag to continue backing up the remaining shards when the current shard fails to backup.
openhab_db-backup.1.suvurwfeo7kk@nuc02    | 2022-04-22.09:39:08 [DEBUG] ** [db-backup] DB Backup Exit Code is 1
```

**Comment by sumnerboy12** [comment]
Hmmm - it appears to have worked/completed, but the final backup `.tar.zst` is only 2kB - has it only backed up the metadata?

```
openhab_db-backup.1.1co9acdzb84a@nuc02    | 2022-04-22.09:42:30 [DEBUG] ** [db-backup] Backup routines started time: 2022-04-22 09:42:30 NZST
openhab_db-backup.1.1co9acdzb84a@nuc02    | 2022-04-22.09:42:30 [DEBUG] ** [db-backup] Preparing to back up everything
openhab_db-backup.1.1co9acdzb84a@nuc02    | 2022-04-22.09:42:30 [NOTICE] ** [db-backup] Dumping Influx database: 'all'
openhab_db-backup.1.1co9acdzb84a@nuc02    | 2022/04/22 09:42:30 backing up metastore to /tmp/backups/influx_all_db_20220422-094230/meta.00
openhab_db-backup.1.1co9acdzb84a@nuc02    | 2022/04/22 09:42:30 No database, retention policy or shard ID given. Full meta store backed up.
openhab_db-backup.1.1co9acdzb84a@nuc02    | 2022/04/22 09:42:30 backup complete:
openhab_db-backup.1.1co9acdzb84a@nuc02    | 2022/04/22 09:42:30         /tmp/backups/influx_all_db_20220422-094230/tmp/backups/influx_all_db_20220422-094230/meta.00
openhab_db-backup.1.1co9acdzb84a@nuc02    | 2022-04-22.09:42:30 [DEBUG] ** [db-backup] DB Backup Exit Code is 0
openhab_db-backup.1.1co9acdzb84a@nuc02    | 2022-04-22.09:42:31 [INFO] ** [db-backup] DB Backup of 'influx_all_db_20220422-094230' completed successfully
openhab_db-backup.1.1co9acdzb84a@nuc02    | 2022-04-22.09:42:31 [NOTICE] ** [db-backup] Creating archive file of 'influx_all_db_20220422-094230' with tar
openhab_db-backup.1.1co9acdzb84a@nuc02    | tar: removing leading '/' from member names
openhab_db-backup.1.1co9acdzb84a@nuc02    | 2022-04-22.09:42:31 [NOTICE] ** [db-backup] Generating MD5 for 'influx_all_db_20220422-094230.tar.zst'
openhab_db-backup.1.1co9acdzb84a@nuc02    | 2022-04-22.09:42:31 [DEBUG] ** [db-backup] MD5: 4658ff68b0456e50541f068cafaac0e4 - influx_all_db_20220422-094230.tar.zst
openhab_db-backup.1.1co9acdzb84a@nuc02    | 2022-04-22.09:42:31 [NOTICE] ** [db-backup] Backup of influx_all_db_20220422-094230.tar.zst created with the size of 2162 bytes
openhab_db-backup.1.1co9acdzb84a@nuc02    | 2022-04-22.09:42:31 [DEBUG] ** [db-backup] Moving backup to filesystem
openhab_db-backup.1.1co9acdzb84a@nuc02    | 2022-04-22.09:42:31 [NOTICE] ** [db-backup] Sending Backup Statistics to Zabbix
openhab_db-backup.1.1co9acdzb84a@nuc02    | Sending failed. Use option -vv for more detailed output.
openhab_db-backup.1.1co9acdzb84a@nuc02    | Sending failed. Use option -vv for more detailed output.
openhab_db-backup.1.1co9acdzb84a@nuc02    | Sending failed. Use option -vv for more detailed output.
openhab_db-backup.1.1co9acdzb84a@nuc02    | Sending failed. Use option -vv for more detailed output.
openhab_db-backup.1.1co9acdzb84a@nuc02    | 2022-04-22.09:42:31 [NOTICE] ** [db-backup] DB Backup for 'all' time taken: Hours: 0 Minutes: 00 Seconds: 01
openhab_db-backup.1.1co9acdzb84a@nuc02    | 2022-04-22.09:42:31 [INFO] ** [db-backup] Backup routines finish time: 2022-04-22 09:42:31 NZST with overall exit code 0
openhab_db-backup.1.1co9acdzb84a@nuc02    | 2022-04-22.09:42:31 [NOTICE] ** [db-backup] Backup routines time taken: Hours: 0 Minutes: 00 Seconds: 01
```

**Comment by sumnerboy12** [comment]
I think you are missing the `-portable` flag in the InfluxDB backup command? And if there is a db name specified it should be `-db $db` not `-bucket $db`...

```
    case "${INFLUX_VERSION,,}" in
        1 )
            for db in ${db_names}; do
                pre_dbbackup
                if [ "${db}" != "justbackupeverything" ] ; then bucket="-bucket $db" ; else db=all ; fi
                target=influx_${db}_${DB_HOST#*//}_${now}
                compression
                print_notice "Dumping Influx database: '${db}'"
                influxd backup ${influx_compression} ${bucket} -host ${DB_HOST}:${DB_PORT} ${EXTRA_OPTS} "${TEMP_LOCATION}"/"${target_dir}"
```

**Comment by tiredofit** [comment]
OK yes, thanks good catch on the V1.  That is fixed in `3.2.3`
As for portable. I haven't ever used the portable flag, but could. Currently it backs up to a temporary directory and then I tar+compress the dir. Let's see how this works and then evaluate if we need portable down the road. Is there a specific extension name that Influx portable uses or is preferred?

**Comment by sumnerboy12** [comment]
I am not sure of any preferred extension name, but every other backup tool/script for InfluxDB seems to use `-portable` - otherwise you end up with a metadata only backup (as I did when using `DB_NAME=ALL`).

I am no expert with this stuff tho...

**Comment by tiredofit** [comment]
You are _way_ more than an expert than I am - I've never even used it :)
Are you able to execute this and get me a directory listing of how a backup looks on an influx server with and without -portable?
They do state now to use Portable unless using legacy backup, which I can't find any information on anwyays, so I'm ok with it, I just want to see what the output is - If it exports to a singular file, or to a directory again.

**Comment by sumnerboy12** [comment]
Ok - so running a backup using `-portable` (for a single database); ```ben@nuc01:~$ ls /var/data/openhab/database-dump/portable/
20220421T225737Z.manifest     20220421T225737Z.s180.tar.gz  20220421T225737Z.s268.tar.gz  20220421T225737Z.s36.tar.gz   20220421T225737Z.s452.tar.gz  20220421T225737Z.s540.tar.gz  20220421T225737Z.s636.tar.gz
20220421T225737Z.meta         20220421T225737Z.s188.tar.gz  20220421T225737Z.s276.tar.gz  20220421T225737Z.s364.tar.gz  20220421T225737Z.s460.tar.gz  20220421T225737Z.s548.tar.gz  20220421T225737Z.s644.tar.gz
20220421T225737Z.s100.tar.gz  20220421T225737Z.s196.tar.gz  20220421T225737Z.s28.tar.gz   20220421T225737Z.s372.tar.gz  20220421T225737Z.s468.tar.gz  20220421T225737Z.s556.tar.gz  20220421T225737Z.s652.tar.gz
20220421T225737Z.s108.tar.gz  20220421T225737Z.s2.tar.gz    20220421T225737Z.s284.tar.gz  20220421T225737Z.s380.tar.gz  20220421T225737Z.s476.tar.gz  20220421T225737Z.s564.tar.gz  20220421T225737Z.s660.tar.gz
20220421T225737Z.s116.tar.gz  20220421T225737Z.s20.tar.gz   20220421T225737Z.s292.tar.gz  20220421T225737Z.s388.tar.gz  20220421T225737Z.s484.tar.gz  20220421T225737Z.s572.tar.gz  20220421T225737Z.s668.tar.gz
20220421T225737Z.s12.tar.gz   20220421T225737Z.s204.tar.gz  20220421T225737Z.s300.tar.gz  20220421T225737Z.s396.tar.gz  20220421T225737Z.s492.tar.gz  20220421T225737Z.s580.tar.gz  20220421T225737Z.s676.tar.gz
20220421T225737Z.s124.tar.gz  20220421T225737Z.s212.tar.gz  20220421T225737Z.s308.tar.gz  20220421T225737Z.s404.tar.gz  20220421T225737Z.s5.tar.gz    20220421T225737Z.s588.tar.gz  20220421T225737Z.s68.tar.gz
20220421T225737Z.s132.tar.gz  20220421T225737Z.s220.tar.gz  20220421T225737Z.s316.tar.gz  20220421T225737Z.s412.tar.gz  20220421T225737Z.s500.tar.gz  20220421T225737Z.s596.tar.gz  20220421T225737Z.s684.tar.gz
20220421T225737Z.s140.tar.gz  20220421T225737Z.s228.tar.gz  20220421T225737Z.s324.tar.gz  20220421T225737Z.s420.tar.gz  20220421T225737Z.s508.tar.gz  20220421T225737Z.s60.tar.gz   20220421T225737Z.s692.tar.gz
20220421T225737Z.s148.tar.gz  20220421T225737Z.s236.tar.gz  20220421T225737Z.s332.tar.gz  20220421T225737Z.s428.tar.gz  20220421T225737Z.s516.tar.gz  20220421T225737Z.s604.tar.gz  20220421T225737Z.s700.tar.gz
20220421T225737Z.s156.tar.gz  20220421T225737Z.s244.tar.gz  20220421T225737Z.s340.tar.gz  20220421T225737Z.s436.tar.gz  20220421T225737Z.s52.tar.gz   20220421T225737Z.s612.tar.gz  20220421T225737Z.s76.tar.gz
20220421T225737Z.s164.tar.gz  20220421T225737Z.s252.tar.gz  20220421T225737Z.s348.tar.gz  20220421T225737Z.s44.tar.gz   20220421T225737Z.s524.tar.gz  20220421T225737Z.s620.tar.gz  20220421T225737Z.s84.tar.gz
20220421T225737Z.s172.tar.gz  20220421T225737Z.s260.tar.gz  20220421T225737Z.s356.tar.gz  20220421T225737Z.s444.tar.gz  20220421T225737Z.s532.tar.gz  20220421T225737Z.s628.tar.gz  20220421T225737Z.s92.tar.gz```

**Comment by sumnerboy12** [comment]
And same backup without `-portable`; ```ben@nuc01:~$ ls /var/data/openhab/database-dump/nonportable/
meta.00                   openhab.autogen.00084.00  openhab.autogen.00180.00  openhab.autogen.00276.00  openhab.autogen.00372.00  openhab.autogen.00468.00  openhab.autogen.00564.00  openhab.autogen.00660.00
openhab.autogen.00002.00  openhab.autogen.00092.00  openhab.autogen.00188.00  openhab.autogen.00284.00  openhab.autogen.00380.00  openhab.autogen.00476.00  openhab.autogen.00572.00  openhab.autogen.00668.00
openhab.autogen.00005.00  openhab.autogen.00100.00  openhab.autogen.00196.00  openhab.autogen.00292.00  openhab.autogen.00388.00  openhab.autogen.00484.00  openhab.autogen.00580.00  openhab.autogen.00676.00
openhab.autogen.00012.00  openhab.autogen.00108.00  openhab.autogen.00204.00  openhab.autogen.00300.00  openhab.autogen.00396.00  openhab.autogen.00492.00  openhab.autogen.00588.00  openhab.autogen.00684.00
openhab.autogen.00020.00  openhab.autogen.00116.00  openhab.autogen.00212.00  openhab.autogen.00308.00  openhab.autogen.00404.00  openhab.autogen.00500.00  openhab.autogen.00596.00  openhab.autogen.00692.00
openhab.autogen.00028.00  openhab.autogen.00124.00  openhab.autogen.00220.00  openhab.autogen.00316.00  openhab.autogen.00412.00  openhab.autogen.00508.00  openhab.autogen.00604.00  openhab.autogen.00700.00
openhab.autogen.00036.00  openhab.autogen.00132.00  openhab.autogen.00228.00  openhab.autogen.00324.00  openhab.autogen.00420.00  openhab.autogen.00516.00  openhab.autogen.00612.00
openhab.autogen.00044.00  openhab.autogen.00140.00  openhab.autogen.00236.00  openhab.autogen.00332.00  openhab.autogen.00428.00  openhab.autogen.00524.00  openhab.autogen.00620.00
openhab.autogen.00052.00  openhab.autogen.00148.00  openhab.autogen.00244.00  openhab.autogen.00340.00  openhab.autogen.00436.00  openhab.autogen.00532.00  openhab.autogen.00628.00
openhab.autogen.00060.00  openhab.autogen.00156.00  openhab.autogen.00252.00  openhab.autogen.00348.00  openhab.autogen.00444.00  openhab.autogen.00540.00  openhab.autogen.00636.00
openhab.autogen.00068.00  openhab.autogen.00164.00  openhab.autogen.00260.00  openhab.autogen.00356.00  openhab.autogen.00452.00  openhab.autogen.00548.00  openhab.autogen.00644.00
openhab.autogen.00076.00  openhab.autogen.00172.00  openhab.autogen.00268.00  openhab.autogen.00364.00  openhab.autogen.00460.00  openhab.autogen.00556.00  openhab.autogen.00652.00```

**Comment by tiredofit** [comment]
OK, I assume they are all just files and not directories.

**Comment by sumnerboy12** [comment]
But if I do a backup with no `-db` specified - i.e. backup everything - I get only a `meta.00` file for the non-portable backup, and a full set of `tar.gz` backups for all dbs when using `-portable`

**Comment by tiredofit** [comment]
OK, makes sense. From their Docs: 

`-db | InfluxDB OSS database name to back up. Optional. If not specified, all databases are backed up when using -portable.`

I wonder how Enterprise works!

**Comment by tiredofit** [comment]
heh heh. ok. `3.2.4` will give you what you need :) Let me know.

**Comment by sumnerboy12** [comment]
Ok - just untared one of those portable files...

```
[tiredofit/db-backup:3.2.2 11:05:56] # tar -xvf /backup/portable/20220421T230003Z.s220.tar.gz 
openhab/autogen/220/000000010-000000002.tsm
```

**Comment by sumnerboy12** [comment]
Ok - tested with `DB_NAME=ALL` and `DB_NAME=openhab` and both appear to be working well. Thanks for the prompt support!!

**Comment by tiredofit** [comment]
Awesome. Glad you are back on track. Sorry about the glitchup here. One day I'll get around to setting up a server to understand more how this works. So little time.

**Comment by sumnerboy12** [comment]
I hear ya mate. Great piece of software tho - thanks for sharing it!

**Comment by EpochalEngineer** [comment]
Has anyone else had this error, specifically 

> Invalid metadata blob, ensure the metadata service is running (default port 8088)

Using these docker images and default unraid templates:
On InfluxDB influxdb:1.8.4-alpine  
tiredofit/db-backup:latest | Version  4.1.0

So far I had to change the port to 8086 even though it is influxdb v1 to get to this message, and also added 8088 to the port forwarding for InfluxDB as it was not standard
