### ISSUE TITLE
Doesn't work with influx

### ISSUE THREAD

**Issue by skylord123** [tiredofit/docker-db-backup#5]
I got this container working with mysql but it fails with my influx databases. I think it has to do with this line:
https://github.com/tiredofit/docker-db-backup/blob/7df0a8200eb7e31e4c90c73fc9889e480c5dde25/install/etc/s6/services/10-db-backup/run#L129

I think `{DBHOST}` needs to be prefixed with $ like `${DBHOST}`. It would also be nice if the port argument was used here (if the database isn't running on default port it wont work).

**Comment by tiredofit** [comment]
Hi @skylord123 - Thanks for the report.
Yes indeed that is the culprit! I've just pushed a new tag 1.10 to this repo, Docker Hub is rebuilding as we speak, and also included in the DB_PORT as requested.

` influxd backup -database $DB -host ${DBHOST} -p ${DBPORT} ${TMPDIR}/${TARGET}`

**Comment by skylord123** [comment]
Wait actually it's still broken. I guess the port argument doesn't exist for this version of influx cli. I will be submitting a PR to fix the issue.
