### ISSUE TITLE
Syntax error in 2.7.0

### ISSUE THREAD

**Issue by SuperMasterPhoenix** [tiredofit/docker-db-backup#69]
### Summary

I just updated the docker image `tiredofit/db-backup` from `2.4.0` to `2.7.0`. Unfortunately this one doesn't work anymore. There seems to be a syntax error in the `run` script.

### Steps to reproduce

Just execute a previously working config. For me this happens for a mariadb and postgres configuration.

### What is the expected *correct* behavior?

The script should work.

### Relevant logs and/or screenshots

```
./run: line 38: syntax error near unexpected token `)'
./run: line 38: `    "mysql" | "MYSQL" | "mariadb" | "MARIADB")'
```

### Environment

- Image version / tag:  tiredofit/db-backup:2.7.0
- Host OS: Synology

    
### Possible fixes

In commit https://github.com/tiredofit/docker-db-backup/commit/eb0ee6166200f6b2d6802341fe890cf97e16f30e there have been two `;;` removed from the `run` script. Possibly this causes the syntax error.

**Comment by the1ts** [comment]
Confirmed, the removal of the `;;` breaks the case statement, inserting `;;` below line 37 of 10-db-backup/run file allows both manual and cron job backups again.

**Comment by tiredofit** [comment]
Sorry about this - that was sloppy on my end. Builds should be working now (at least with :latest). I'm away for a few days and will return with a tagged release then.

**Comment by alwynpan** [comment]
@tiredofit Could you please make a release? The image on the Docker Hub still fails.
